questions:
  paths:
    ru_RU: '/questions_ru.csv'
    en: '/questions_en.csv'
  correct-answers: 3

application:
  locale: ru_RU

spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"